"""Self-probing uncertainty: calculation only.

Given the verification model's raw text response to a self-probing prompt
(asking it to score its own confidence 0-100 that a generated SQL query is
correct), computes an uncertainty score. Does not run any model inference.
"""
import math
from typing import Optional

from text_to_sql.prompt_templates.verification_task.SelfProbingPrompt import SelfProbingPrompt


def calculate_self_probing_uncertainty(
    verification_response: str,
    verification_prompt: SelfProbingPrompt,
    predicted_sql: Optional[str] = None,
) -> Optional[float]:
    """Compute uncertainty as ``1 - confidence`` from a self-probing response.

    Args:
        verification_response: raw text generated by the verification model
            in response to a self-probing prompt (expected to contain a
            number between 0 and 100).
        verification_prompt: prompt template used to parse the confidence
            score out of ``verification_response``.
        predicted_sql: the SQL query that was probed. When ``None`` or NaN
            (i.e. no SQL could be generated in the first place), uncertainty
            is not computable and ``None`` is returned without parsing.

    Returns:
        Uncertainty in [0, 1], or None if the SQL was missing or the
        confidence score could not be parsed from the response.
    """
    if predicted_sql is None or (isinstance(predicted_sql, float) and math.isnan(predicted_sql)):
        return None

    confidence = verification_prompt.parse_confidence(verification_response)
    return 1.0 - confidence if confidence is not None else None
